// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql"

	"github.com/ananthakumaran/paisa/internal/config"
	"github.com/shopspring/decimal"
)

type Portfolio struct {
	ID                int64
	CommodityType     config.CommodityType
	ParentCommodityID sql.NullString
	SecurityID        sql.NullString
	SecurityName      sql.NullString
	SecurityType      sql.NullString
	SecurityRating    sql.NullString
	SecurityIndustry  sql.NullString
	Percentage        decimal.Decimal
}

type Posting struct {
	ID                   int64
	TransactionID        sql.NullString
	Date                 sql.NullTime
	Payee                sql.NullString
	Account              sql.NullString
	Commodity            sql.NullString
	Quantity             decimal.Decimal
	Amount               decimal.Decimal
	OriginalAmount       decimal.Decimal
	Status               sql.NullString
	TagRecurring         sql.NullString
	TagPeriod            sql.NullString
	TransactionBeginLine sql.NullInt64
	TransactionEndLine   sql.NullInt64
	FileName             sql.NullString
	Forecast             sql.NullBool
	Note                 sql.NullString
	TransactionNote      sql.NullString
	TransactionHash      sql.NullString
}

type Price struct {
	ID             int64
	Date           sql.NullTime
	CommodityType  config.CommodityType
	CommodityID    sql.NullString
	CommodityName  sql.NullString
	QuoteCommodity sql.NullString
	Value          decimal.Decimal
	Source         sql.NullString
}
