// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"
	"database/sql"

	"github.com/ananthakumaran/paisa/internal/config"
)

type Querier interface {
	DeleteAllPostings(ctx context.Context) error
	DeletePortfoliosByTypeAndParent(ctx context.Context, arg DeletePortfoliosByTypeAndParentParams) error
	DeletePostingsByTransactionID(ctx context.Context, transactionID sql.NullString) error
	DeletePricesByType(ctx context.Context, commodityType config.CommodityType) error
	FindPriceByDateBaseQuote(ctx context.Context, arg FindPriceByDateBaseQuoteParams) (Price, error)
	GroupPostingSums(ctx context.Context, arg GroupPostingSumsParams) ([]GroupPostingSumsRow, error)
	InsertPortfolio(ctx context.Context, arg InsertPortfolioParams) error
	InsertPosting(ctx context.Context, arg InsertPostingParams) error
	ListLatestPrices(ctx context.Context, arg ListLatestPricesParams) ([]Price, error)
	ListPortfolioParentCommodityIDs(ctx context.Context) ([]sql.NullString, error)
	ListPortfoliosByParent(ctx context.Context, parentCommodityID sql.NullString) ([]Portfolio, error)
	ListPostingTransactionHashes(ctx context.Context) ([]ListPostingTransactionHashesRow, error)
	ListPostingsAsc(ctx context.Context, arg ListPostingsAscParams) ([]Posting, error)
	ListPostingsDesc(ctx context.Context, arg ListPostingsDescParams) ([]Posting, error)
	ListPrices(ctx context.Context, arg ListPricesParams) ([]Price, error)
	UpsertPrice(ctx context.Context, arg UpsertPriceParams) error
}

var _ Querier = (*Queries)(nil)
