// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlcdb

import (
	"context"
	"database/sql"

	"github.com/ananthakumaran/paisa/internal/config"
	"github.com/shopspring/decimal"
)

const deleteAllPostings = `-- name: DeleteAllPostings :exec
DELETE FROM postings
`

func (q *Queries) DeleteAllPostings(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllPostings)
	return err
}

const deletePortfoliosByTypeAndParent = `-- name: DeletePortfoliosByTypeAndParent :exec
DELETE FROM portfolios
WHERE commodity_type = ?1
  AND parent_commodity_id = ?2
`

type DeletePortfoliosByTypeAndParentParams struct {
	CommodityType     config.CommodityType
	ParentCommodityID sql.NullString
}

func (q *Queries) DeletePortfoliosByTypeAndParent(ctx context.Context, arg DeletePortfoliosByTypeAndParentParams) error {
	_, err := q.db.ExecContext(ctx, deletePortfoliosByTypeAndParent, arg.CommodityType, arg.ParentCommodityID)
	return err
}

const deletePostingsByTransactionID = `-- name: DeletePostingsByTransactionID :exec
DELETE FROM postings
WHERE transaction_id = ?1
`

func (q *Queries) DeletePostingsByTransactionID(ctx context.Context, transactionID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deletePostingsByTransactionID, transactionID)
	return err
}

const deletePricesByType = `-- name: DeletePricesByType :exec
DELETE FROM prices
WHERE commodity_type = ?1
`

func (q *Queries) DeletePricesByType(ctx context.Context, commodityType config.CommodityType) error {
	_, err := q.db.ExecContext(ctx, deletePricesByType, commodityType)
	return err
}

const findPriceByDateBaseQuote = `-- name: FindPriceByDateBaseQuote :one
SELECT id, date, commodity_type, commodity_id, commodity_name, quote_commodity, value, source
FROM prices
WHERE commodity_name = ?1
  AND quote_commodity = ?2
  AND date <= ?3
ORDER BY date DESC
LIMIT 1
`

type FindPriceByDateBaseQuoteParams struct {
	BaseCommodity  sql.NullString
	QuoteCommodity sql.NullString
	AtOrBefore     sql.NullTime
}

func (q *Queries) FindPriceByDateBaseQuote(ctx context.Context, arg FindPriceByDateBaseQuoteParams) (Price, error) {
	row := q.db.QueryRowContext(ctx, findPriceByDateBaseQuote, arg.BaseCommodity, arg.QuoteCommodity, arg.AtOrBefore)
	var i Price
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.CommodityType,
		&i.CommodityID,
		&i.CommodityName,
		&i.QuoteCommodity,
		&i.Value,
		&i.Source,
	)
	return i, err
}

const groupPostingSums = `-- name: GroupPostingSums :many
SELECT
    account,
    commodity,
    CAST(SUM(amount) AS TEXT) AS amount,
    CAST(SUM(quantity) AS TEXT) AS quantity
FROM postings
WHERE forecast = ?1
  AND (?2 = 0 OR date >= ?3)
  AND (?4 = 0 OR date <= ?5)
  AND (?6 = '' OR status = ?6)
  AND (?7 = 0 OR amount > 0)
  AND (?8 = '' OR account = ?8)
  AND (json_array_length(?9) = 0 OR commodity IN (SELECT value FROM json_each(?9)))
  AND (json_array_length(?10) = 0 OR EXISTS (
        SELECT 1 FROM json_each(?10)
        WHERE postings.account = value OR postings.account LIKE value || ':%'
    ))
  AND (json_array_length(?11) = 0 OR NOT EXISTS (
        SELECT 1 FROM json_each(?11)
        WHERE postings.account = value OR postings.account LIKE value || ':%'
    ))
  AND (json_array_length(?12) = 0 OR EXISTS (
        SELECT 1 FROM json_each(?12)
        WHERE postings.account LIKE value
    ))
  AND (json_array_length(?13) = 0 OR NOT EXISTS (
        SELECT 1 FROM json_each(?13)
        WHERE postings.account LIKE value
    ))
  AND (json_array_length(?14) = 0 OR account NOT IN (SELECT value FROM json_each(?14)))
GROUP BY account, commodity
ORDER BY account ASC, commodity ASC
`

type GroupPostingSumsParams struct {
	Forecast          sql.NullBool
	Column2           interface{}
	Date              sql.NullTime
	Column4           interface{}
	Date_2            sql.NullTime
	Column6           interface{}
	Column7           interface{}
	Column8           interface{}
	JsonArrayLength   interface{}
	JsonArrayLength_2 interface{}
	JsonArrayLength_3 interface{}
	JsonArrayLength_4 interface{}
	JsonArrayLength_5 interface{}
	JsonArrayLength_6 interface{}
}

type GroupPostingSumsRow struct {
	Account   sql.NullString
	Commodity sql.NullString
	Amount    string
	Quantity  string
}

func (q *Queries) GroupPostingSums(ctx context.Context, arg GroupPostingSumsParams) ([]GroupPostingSumsRow, error) {
	rows, err := q.db.QueryContext(ctx, groupPostingSums,
		arg.Forecast,
		arg.Column2,
		arg.Date,
		arg.Column4,
		arg.Date_2,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.JsonArrayLength,
		arg.JsonArrayLength_2,
		arg.JsonArrayLength_3,
		arg.JsonArrayLength_4,
		arg.JsonArrayLength_5,
		arg.JsonArrayLength_6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupPostingSumsRow
	for rows.Next() {
		var i GroupPostingSumsRow
		if err := rows.Scan(
			&i.Account,
			&i.Commodity,
			&i.Amount,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPortfolio = `-- name: InsertPortfolio :exec
INSERT INTO portfolios (
    commodity_type,
    parent_commodity_id,
    security_id,
    security_name,
    security_type,
    security_rating,
    security_industry,
    percentage
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8
)
`

type InsertPortfolioParams struct {
	CommodityType     config.CommodityType
	ParentCommodityID sql.NullString
	SecurityID        sql.NullString
	SecurityName      sql.NullString
	SecurityType      sql.NullString
	SecurityRating    sql.NullString
	SecurityIndustry  sql.NullString
	Percentage        decimal.Decimal
}

func (q *Queries) InsertPortfolio(ctx context.Context, arg InsertPortfolioParams) error {
	_, err := q.db.ExecContext(ctx, insertPortfolio,
		arg.CommodityType,
		arg.ParentCommodityID,
		arg.SecurityID,
		arg.SecurityName,
		arg.SecurityType,
		arg.SecurityRating,
		arg.SecurityIndustry,
		arg.Percentage,
	)
	return err
}

const insertPosting = `-- name: InsertPosting :exec
INSERT INTO postings (
    transaction_id,
    date,
    payee,
    account,
    commodity,
    quantity,
    amount,
    original_amount,
    status,
    tag_recurring,
    tag_period,
    transaction_begin_line,
    transaction_end_line,
    file_name,
    forecast,
    note,
    transaction_note,
    transaction_hash
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14,
    ?15,
    ?16,
    ?17,
    ?18
)
`

type InsertPostingParams struct {
	TransactionID        sql.NullString
	Date                 sql.NullTime
	Payee                sql.NullString
	Account              sql.NullString
	Commodity            sql.NullString
	Quantity             decimal.Decimal
	Amount               decimal.Decimal
	OriginalAmount       decimal.Decimal
	Status               sql.NullString
	TagRecurring         sql.NullString
	TagPeriod            sql.NullString
	TransactionBeginLine sql.NullInt64
	TransactionEndLine   sql.NullInt64
	FileName             sql.NullString
	Forecast             sql.NullBool
	Note                 sql.NullString
	TransactionNote      sql.NullString
	TransactionHash      sql.NullString
}

func (q *Queries) InsertPosting(ctx context.Context, arg InsertPostingParams) error {
	_, err := q.db.ExecContext(ctx, insertPosting,
		arg.TransactionID,
		arg.Date,
		arg.Payee,
		arg.Account,
		arg.Commodity,
		arg.Quantity,
		arg.Amount,
		arg.OriginalAmount,
		arg.Status,
		arg.TagRecurring,
		arg.TagPeriod,
		arg.TransactionBeginLine,
		arg.TransactionEndLine,
		arg.FileName,
		arg.Forecast,
		arg.Note,
		arg.TransactionNote,
		arg.TransactionHash,
	)
	return err
}

const listLatestPrices = `-- name: ListLatestPrices :many
SELECT p1.id, p1.date, p1.commodity_type, p1.commodity_id, p1.commodity_name, p1.quote_commodity, p1.value, p1.source
FROM prices AS p1
WHERE (?1 = '' OR p1.commodity_name = ?1)
  AND (?2 = '' OR p1.quote_commodity = ?2)
  AND (?3 = '' OR p1.source = ?3)
  AND (?4 = 0 OR p1.date >= ?5)
  AND (?6 = 0 OR p1.date <= ?7)
  AND NOT EXISTS (
        SELECT 1
        FROM prices AS p2
        WHERE p2.commodity_name = p1.commodity_name
          AND (?1 = '' OR p2.commodity_name = ?1)
          AND (?2 = '' OR p2.quote_commodity = ?2)
          AND (?3 = '' OR p2.source = ?3)
          AND (?4 = 0 OR p2.date >= ?5)
          AND (?6 = 0 OR p2.date <= ?7)
          AND (
                p2.date > p1.date OR
                (p2.date = p1.date AND p2.quote_commodity < p1.quote_commodity) OR
                (p2.date = p1.date AND p2.quote_commodity = p1.quote_commodity AND p2.source < p1.source) OR
                (p2.date = p1.date AND p2.quote_commodity = p1.quote_commodity AND p2.source = p1.source AND p2.id > p1.id)
          )
    )
ORDER BY date ASC, commodity_name ASC, quote_commodity ASC, source ASC
`

type ListLatestPricesParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
	Column4 interface{}
	Date    sql.NullTime
	Column6 interface{}
	Date_2  sql.NullTime
}

func (q *Queries) ListLatestPrices(ctx context.Context, arg ListLatestPricesParams) ([]Price, error) {
	rows, err := q.db.QueryContext(ctx, listLatestPrices,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Date,
		arg.Column6,
		arg.Date_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Price
	for rows.Next() {
		var i Price
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.CommodityType,
			&i.CommodityID,
			&i.CommodityName,
			&i.QuoteCommodity,
			&i.Value,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortfolioParentCommodityIDs = `-- name: ListPortfolioParentCommodityIDs :many
SELECT DISTINCT parent_commodity_id
FROM portfolios
ORDER BY parent_commodity_id ASC
`

func (q *Queries) ListPortfolioParentCommodityIDs(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listPortfolioParentCommodityIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var parent_commodity_id sql.NullString
		if err := rows.Scan(&parent_commodity_id); err != nil {
			return nil, err
		}
		items = append(items, parent_commodity_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortfoliosByParent = `-- name: ListPortfoliosByParent :many
SELECT id, commodity_type, parent_commodity_id, security_id, security_name, security_type, security_rating, security_industry, percentage
FROM portfolios
WHERE parent_commodity_id = ?1
ORDER BY security_name ASC, security_id ASC
`

func (q *Queries) ListPortfoliosByParent(ctx context.Context, parentCommodityID sql.NullString) ([]Portfolio, error) {
	rows, err := q.db.QueryContext(ctx, listPortfoliosByParent, parentCommodityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Portfolio
	for rows.Next() {
		var i Portfolio
		if err := rows.Scan(
			&i.ID,
			&i.CommodityType,
			&i.ParentCommodityID,
			&i.SecurityID,
			&i.SecurityName,
			&i.SecurityType,
			&i.SecurityRating,
			&i.SecurityIndustry,
			&i.Percentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostingTransactionHashes = `-- name: ListPostingTransactionHashes :many
SELECT DISTINCT transaction_id, transaction_hash
FROM postings
ORDER BY transaction_id ASC
`

type ListPostingTransactionHashesRow struct {
	TransactionID   sql.NullString
	TransactionHash sql.NullString
}

func (q *Queries) ListPostingTransactionHashes(ctx context.Context) ([]ListPostingTransactionHashesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostingTransactionHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostingTransactionHashesRow
	for rows.Next() {
		var i ListPostingTransactionHashesRow
		if err := rows.Scan(&i.TransactionID, &i.TransactionHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostingsAsc = `-- name: ListPostingsAsc :many
SELECT
    id,
    transaction_id,
    date,
    payee,
    account,
    commodity,
    quantity,
    amount,
    original_amount,
    status,
    tag_recurring,
    tag_period,
    transaction_begin_line,
    transaction_end_line,
    file_name,
    forecast,
    note,
    transaction_note,
    transaction_hash
FROM postings
WHERE forecast = ?1
  AND (?2 = 0 OR date >= ?3)
  AND (?4 = 0 OR date <= ?5)
  AND (?6 = '' OR status = ?6)
  AND (?7 = 0 OR amount > 0)
  AND (?8 = '' OR account = ?8)
  AND (json_array_length(?9) = 0 OR commodity IN (SELECT value FROM json_each(?9)))
  AND (json_array_length(?10) = 0 OR EXISTS (
        SELECT 1 FROM json_each(?10)
        WHERE postings.account = value OR postings.account LIKE value || ':%'
    ))
  AND (json_array_length(?11) = 0 OR NOT EXISTS (
        SELECT 1 FROM json_each(?11)
        WHERE postings.account = value OR postings.account LIKE value || ':%'
    ))
  AND (json_array_length(?12) = 0 OR EXISTS (
        SELECT 1 FROM json_each(?12)
        WHERE postings.account LIKE value
    ))
  AND (json_array_length(?13) = 0 OR NOT EXISTS (
        SELECT 1 FROM json_each(?13)
        WHERE postings.account LIKE value
    ))
  AND (json_array_length(?14) = 0 OR account NOT IN (SELECT value FROM json_each(?14)))
ORDER BY date ASC, amount DESC, account ASC
LIMIT CASE WHEN ?16 > 0 THEN ?16 ELSE -1 END
OFFSET ?15
`

type ListPostingsAscParams struct {
	Forecast          sql.NullBool
	Column2           interface{}
	Date              sql.NullTime
	Column4           interface{}
	Date_2            sql.NullTime
	Column6           interface{}
	Column7           interface{}
	Column8           interface{}
	JsonArrayLength   interface{}
	JsonArrayLength_2 interface{}
	JsonArrayLength_3 interface{}
	JsonArrayLength_4 interface{}
	JsonArrayLength_5 interface{}
	JsonArrayLength_6 interface{}
	Offset            int64
	Column16          interface{}
}

func (q *Queries) ListPostingsAsc(ctx context.Context, arg ListPostingsAscParams) ([]Posting, error) {
	rows, err := q.db.QueryContext(ctx, listPostingsAsc,
		arg.Forecast,
		arg.Column2,
		arg.Date,
		arg.Column4,
		arg.Date_2,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.JsonArrayLength,
		arg.JsonArrayLength_2,
		arg.JsonArrayLength_3,
		arg.JsonArrayLength_4,
		arg.JsonArrayLength_5,
		arg.JsonArrayLength_6,
		arg.Offset,
		arg.Column16,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Posting
	for rows.Next() {
		var i Posting
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.Date,
			&i.Payee,
			&i.Account,
			&i.Commodity,
			&i.Quantity,
			&i.Amount,
			&i.OriginalAmount,
			&i.Status,
			&i.TagRecurring,
			&i.TagPeriod,
			&i.TransactionBeginLine,
			&i.TransactionEndLine,
			&i.FileName,
			&i.Forecast,
			&i.Note,
			&i.TransactionNote,
			&i.TransactionHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostingsDesc = `-- name: ListPostingsDesc :many
SELECT
    id,
    transaction_id,
    date,
    payee,
    account,
    commodity,
    quantity,
    amount,
    original_amount,
    status,
    tag_recurring,
    tag_period,
    transaction_begin_line,
    transaction_end_line,
    file_name,
    forecast,
    note,
    transaction_note,
    transaction_hash
FROM postings
WHERE forecast = ?1
  AND (?2 = 0 OR date >= ?3)
  AND (?4 = 0 OR date <= ?5)
  AND (?6 = '' OR status = ?6)
  AND (?7 = 0 OR amount > 0)
  AND (?8 = '' OR account = ?8)
  AND (json_array_length(?9) = 0 OR commodity IN (SELECT value FROM json_each(?9)))
  AND (json_array_length(?10) = 0 OR EXISTS (
        SELECT 1 FROM json_each(?10)
        WHERE postings.account = value OR postings.account LIKE value || ':%'
    ))
  AND (json_array_length(?11) = 0 OR NOT EXISTS (
        SELECT 1 FROM json_each(?11)
        WHERE postings.account = value OR postings.account LIKE value || ':%'
    ))
  AND (json_array_length(?12) = 0 OR EXISTS (
        SELECT 1 FROM json_each(?12)
        WHERE postings.account LIKE value
    ))
  AND (json_array_length(?13) = 0 OR NOT EXISTS (
        SELECT 1 FROM json_each(?13)
        WHERE postings.account LIKE value
    ))
  AND (json_array_length(?14) = 0 OR account NOT IN (SELECT value FROM json_each(?14)))
ORDER BY date DESC, amount DESC, account ASC
LIMIT CASE WHEN ?16 > 0 THEN ?16 ELSE -1 END
OFFSET ?15
`

type ListPostingsDescParams struct {
	Forecast          sql.NullBool
	Column2           interface{}
	Date              sql.NullTime
	Column4           interface{}
	Date_2            sql.NullTime
	Column6           interface{}
	Column7           interface{}
	Column8           interface{}
	JsonArrayLength   interface{}
	JsonArrayLength_2 interface{}
	JsonArrayLength_3 interface{}
	JsonArrayLength_4 interface{}
	JsonArrayLength_5 interface{}
	JsonArrayLength_6 interface{}
	Offset            int64
	Column16          interface{}
}

func (q *Queries) ListPostingsDesc(ctx context.Context, arg ListPostingsDescParams) ([]Posting, error) {
	rows, err := q.db.QueryContext(ctx, listPostingsDesc,
		arg.Forecast,
		arg.Column2,
		arg.Date,
		arg.Column4,
		arg.Date_2,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.JsonArrayLength,
		arg.JsonArrayLength_2,
		arg.JsonArrayLength_3,
		arg.JsonArrayLength_4,
		arg.JsonArrayLength_5,
		arg.JsonArrayLength_6,
		arg.Offset,
		arg.Column16,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Posting
	for rows.Next() {
		var i Posting
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.Date,
			&i.Payee,
			&i.Account,
			&i.Commodity,
			&i.Quantity,
			&i.Amount,
			&i.OriginalAmount,
			&i.Status,
			&i.TagRecurring,
			&i.TagPeriod,
			&i.TransactionBeginLine,
			&i.TransactionEndLine,
			&i.FileName,
			&i.Forecast,
			&i.Note,
			&i.TransactionNote,
			&i.TransactionHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrices = `-- name: ListPrices :many
SELECT id, date, commodity_type, commodity_id, commodity_name, quote_commodity, value, source
FROM prices
WHERE (?1 = '' OR commodity_name = ?1)
  AND (?2 = '' OR quote_commodity = ?2)
  AND (?3 = '' OR source = ?3)
  AND (?4 = 0 OR date >= ?5)
  AND (?6 = 0 OR date <= ?7)
ORDER BY date ASC, commodity_name ASC, quote_commodity ASC, source ASC
`

type ListPricesParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
	Column4 interface{}
	Date    sql.NullTime
	Column6 interface{}
	Date_2  sql.NullTime
}

func (q *Queries) ListPrices(ctx context.Context, arg ListPricesParams) ([]Price, error) {
	rows, err := q.db.QueryContext(ctx, listPrices,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Date,
		arg.Column6,
		arg.Date_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Price
	for rows.Next() {
		var i Price
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.CommodityType,
			&i.CommodityID,
			&i.CommodityName,
			&i.QuoteCommodity,
			&i.Value,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPrice = `-- name: UpsertPrice :exec
INSERT INTO prices (
    date,
    commodity_type,
    commodity_id,
    commodity_name,
    quote_commodity,
    value,
    source
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
)
ON CONFLICT (commodity_type, date, commodity_name, quote_commodity) DO UPDATE SET
    commodity_id = excluded.commodity_id,
    value = excluded.value,
    source = excluded.source
`

type UpsertPriceParams struct {
	Date           sql.NullTime
	CommodityType  config.CommodityType
	CommodityID    sql.NullString
	CommodityName  sql.NullString
	QuoteCommodity sql.NullString
	Value          decimal.Decimal
	Source         sql.NullString
}

func (q *Queries) UpsertPrice(ctx context.Context, arg UpsertPriceParams) error {
	_, err := q.db.ExecContext(ctx, upsertPrice,
		arg.Date,
		arg.CommodityType,
		arg.CommodityID,
		arg.CommodityName,
		arg.QuoteCommodity,
		arg.Value,
		arg.Source,
	)
	return err
}
